/*1 . An e-commerce website wishes to find the lucky customer who will be eligible for full value cash back. For this purpose, a number N is fed to the system. It will return another number that is calculated by an algorithm. In the algorithm, a sequence is generated, in which each number is the sum of the two preceding numbers. Initially the sequence will have two 1’s in it. The system will return the Nth numberfrom the generated sequence which is treated as the order ID. The lucky customer will be the one who has placed that order. Write an algorithm to help the website find the lucky customer. Input:The input consists of an integer token, representing the number fed to the system (N). Output:Print an integer representing the order ID of the lucky customer. Example Input: 8 Output: 21
Explanation: The sequence generated by the system will be 1,1,2,3,5,8,13,21. The 8th number in the sequence is 21. The lucky customer is the one who has placed the order with order ID 21. 
Test case 2: Input:7 Expected Return Value: 13*/
import java.util.Scanner;
public class luckycustomer{
    public static void main(String args[]){
        Scanner sc = new Scanner(System.in);
        System.out.println("enter the number ");
        int n = sc.nextInt();
        if(n<=0){
            System.out.println("the entered number is invalid");
        }
        else{
            int result = fibonacci(n);
            System.out.println("the order id of lucky customer is :"+result);
        }
    }
    public static int fibonacci(int N){
        if(N==1||N==2){
            return 1;
        }
        int a =1;
        int b =1;
        int fibonaccis =0;
        for(int i =0;i<=N;i++){
            fibonaccis = a+b;
            a=b;
            b=fibonaccis;
        }
         return fibonaccis;
    }
}
/*output:
enter the number 
7
the order id of lucky customer is :13*/